apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
metadata:
  #recommended format <group>.<resource>.<unique name within the namespace>
  name: topo.kubenet.dev.topologies.nodelink 
spec: 
  # conditionType used by the reconciler
  conditionType: LinkNodeReady
  # for resource the reconciler acts upon
  for: 
    group: topo.kubenet.dev
    version: v1alpha1
    kind: Topology
    selector: {}
  # own resources (aka children of the for resource)
  owns:
  - group: infra.kuid.dev
    version: v1alpha1
    kind: Node
  - group: infra.kuid.dev
    version: v1alpha1
    kind: Link