apiVersion: choreo.kform.dev/v1alpha1
kind: UpstreamRef
metadata:
  name: kubenet
spec:
  type: crd
  url: https://github.com/kubenet-dev/apis.git
  ref:
    type: hash
    name: bdafcb27c7941828b73d761ccc1dfa9f426c5324
  includes:
  - device.network.kubenet.dev_nodetemplates
  - topo.kubenet.dev_topologies
  