apiVersion: choreo.kform.dev/v1alpha1
kind: UpstreamRef
metadata:
  name: kubenet
spec:
  type: crd
  url: https://github.com/kubenet-dev/apis.git
  ref:
    type: hash
    name: 5c50179c3bf64ca064cae64837c81f9c56d5c8e0
  includes:
  - device.network.kubenet.dev_nodetemplates
  - topo.kubenet.dev_topologies
  