apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
# name can be inferred from the filename or from the for resource
metadata:
  name: device.network.kubenet.dev.subinterfaaces.bfd
spec: 
  conditionType: BFDReady
  for: 
    group: device.network.kubenet.dev
    version: v1alpha1
    kind: SubInterface
    selector: {}
  owns:
  - group: device.network.kubenet.dev
    version: v1alpha1
    kind: BFD
