apiVersion: topo.kubenet.dev/v1alpha1
kind: Topology
metadata:
  name: kubenet
  namespace: default
spec:
  defaults:
    provider: srlinux.nokia.com
    platformType: ixrd3
    version: 24.7.2
    region: region1
    site: us-east
  nodes:
  - name: node1
  - name: node2
  links:
  - endpoints:
    - {node: node1, port: 1, endpoint: 1, adaptor: "sfp"}
    - {node: node2, port: 1, endpoint: 1, adaptor: "sfp"}
  - endpoints:
    - {node: node1, port: 2, endpoint: 1, adaptor: "sfp"}
    - {node: node2, port: 2, endpoint: 1, adaptor: "sfp"}
